defaults: &defaults
  # https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=me
  sample_access_token: "CAACEdEose0cBABWJ5RZCHeESXajfwo6GZBhEnB6APYZBKASWdkHuV1E25HwCSNbmuJzvsJkgOmsdWXZBRk09tCyDiVkOPoZAbYNBZA6XewkRRf9HmlT77giyLReAPZCxjZCaesl418ZCVISh7ZABOOYtjBczlGR3Ozku7f5dSQbLIIzLY7gz9SZChZAqB0iGwgQl8ToZD"
  gender:
    male: 1
    female: 2
  facebook:
    gender:
      male: "male"
      female: "female"
  google:
    cloud_messaging:
      authorization_key: "AIzaSyCkBSgSGrHLC7vdQ9aRc9lbZmijk3JKkDM"
      content_type_json: "application/json"

development:
  <<: *defaults

test:
  <<: *defaults
